apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  selector:
    matchLabels:
      app: notification-pod
  template:
    metadata:
      labels:
        app: notification-pod
    spec:
      containers:
      - name: notification-container
        image: benhassan98/notification-service-image
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-pod
  ports:
  - name: notification-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080
                                                                                                                                    
